export default {
  data() {
    return {
      carBrands: [
        {'id': 'acura', 'title': 'Acura'},
        {'id': 'alfa_romeo', 'title': 'Alfa Romeo'},
        {'id': 'audi', 'title': 'Audi'},
        {'id': 'bmw', 'title': 'BMW'},
        {'id': 'cadillac', 'title': 'Cadillac'},
        {'id': 'chery', 'title': 'Chery'},
        {'id': 'chevrolet', 'title': 'Chevrolet'},
        {'id': 'chrysler', 'title': 'Chrysler'},
        {'id': 'citroen', 'title': 'Citroen'},
        {'id': 'dacia', 'title': 'Dacia'},
        {'id': 'daewoo', 'title': 'Daewoo'},
        {'id': 'daf', 'title': 'DAF'},
        {'id': 'dodge', 'title': 'Dodge'},
        {'id': 'fiat', 'title': 'Fiat'},
        {'id': 'ford', 'title': 'Ford'},
        {'id': 'geely', 'title': 'Geely'},
        {'id': 'honda', 'title': 'Honda'},
        {'id': 'hyundai', 'title': 'Hyundai'},
        {'id': 'infinity', 'title': 'Infinity'},
        {'id': 'iveco', 'title': 'Iveco'},
        {'id': 'jaguar', 'title': 'Jaguar'},
        {'id': 'jeep', 'title': 'Jeep'},
        {'id': 'kia', 'title': 'Kia'},
        {'id': 'lada', 'title': 'Lada'},
        {'id': 'land_rover', 'title': 'Land Rover'},
        {'id': 'lexus', 'title': 'Lexus'},
        {'id': 'man', 'title': 'MAN'},
        {'id': 'mazda', 'title': 'Mazda'},
        {'id': 'mercedes', 'title': 'Mercedes'},
        {'id': 'mini', 'title': 'Mini'},
        {'id': 'mitsubishi', 'title': 'Mitsubishi'},
        {'id': 'nissan', 'title': 'Nissan'},
        {'id': 'opel', 'title': 'Opel'},
        {'id': 'peugeot', 'title': 'Peugeot'},
        {'id': 'porsche', 'title': 'Porsche'},
        {'id': 'renault', 'title': 'Renault'},
        {'id': 'rover', 'title': 'Rover'},
        {'id': 'saab', 'title': 'Saab'},
        {'id': 'seat', 'title': 'Seat'},
        {'id': 'skoda', 'title': 'Skoda'},
        {'id': 'smart', 'title': 'Smart'},
        {'id': 'ssang_yong', 'title': 'SsangYong'},
        {'id': 'subaru', 'title': 'Subaru'},
        {'id': 'suzuki', 'title': 'Suzuki'},
        {'id': 'tesla', 'title': 'Tesla'},
        {'id': 'toyota', 'title': 'Toyota'},
        {'id': 'volkswagen', 'title': 'Volkswagen'},
        {'id': 'volvo', 'title': 'Volvo'},
        {'id': 'vaz', 'title': 'ВАЗ'},
        {'id': 'gaz', 'title': 'ГАЗ'},
        {'id': 'zaz', 'title': 'ЗАЗ'},
        {'id': 'uaz', 'title': 'УАЗ'},
        {'id': 'niva', 'title': 'Нива'},
        {'id': 'moskvich', 'title': 'Москвич'},
        {'id': 'zil', 'title': 'ЗИЛ'},
        {'id': 'other', 'title': 'Інша'},
      ]
    }
  }
}